# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:

    working_directory: ~/calculator

    docker:
       - image: selenium/standalone-chrome

    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: v1-calculator-{{ checksum "~/calculator/.circleci/config.yml" }}

      # Install Ruby and dependencies needed for gems
      # - run: |
      #     sudo apt update
      #     sudo apt-get -y install ruby-dev
      #     sudo apt-get -y install make
      #     sudo apt-get -y install gcc

      # # Update apt and download package installers
      - run: |
          sudo apt update
          mkdir -p ~/calculator/packages
          cd ~/calculator/packages
          sudo apt-get download ruby-dev
          sudo apt-get download make
          sudo apt-get download gcc
          sudo apt-get download firefox

      # Download & setup geckodriver
      - run: |
          wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
          gunzip -c geckodriver.tar.gz | tar xopf -
          chmod +x geckodriver
          mkdir -p ~/calculator/gecko/
          mv geckodriver ~/calculator/gecko/

      # # Install cached packages and update PATH
      - run: |
          sudo apt-get -y install gdebi-core
          sudo gdebi --non-interactive ./packages/ruby-dev*
          sudo gdebi --non-interactive ./packages/make*
          sudo gdebi --non-interactive ./packages/gcc*
          sudo gdebi --non-interactive ./packages/firefox*
          echo 'export PATH=~/calculator/gecko:$PATH' >> $BASH_ENV

      # Install cached packages and update PATH
      # - run: |
      #     sudo apt -y install ./packages/ruby-dev*
      #     sudo apt -y install ./packages/make*
      #     sudo apt -y install ./packages/gcc*
      #     sudo apt -y install ./packages/firefox*
      #     echo 'export PATH=~/calculator/gecko:$PATH' >> $BASH_ENV

      # Install bundler
      - run: sudo gem install bundler

      # Bundle install dependencies
      # - run: bundle install --path vendor/bundle
      - run: bundle install

      # # Download & setup geckodriver
      # - run: |
      #     wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
      #     gunzip -c geckodriver.tar.gz | tar xopf -
      #     chmod +x geckodriver
      #     mkdir ~/calculator/gecko/
      #     mv geckodriver ~/calculator/gecko/
      #     echo 'export PATH=~/calculator/gecko:$PATH' >> $BASH_ENV

      # Store bundle cache
      - type: cache-save
        key: v1-calculator-{{ checksum "~/calculator/.circleci/config.yml" }}
        paths:
          - ./vendor/bundle
          - ./packages
          - ./gecko

      # Create directory for tests
      - run: mkdir -p ~/calculator/test-results/

      # Run tests
      - run: rake test

      # collect reports
      - store_test_results:
          path: ~/calculator/test-results
      # - store_artifacts:
      #     path: ~/calculator/test-results
      #     destination: test-results