# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/calculator
    docker:
       # - image: circleci/ruby:2.4.1-node-browsers
       # - image: circleci/ruby:2.4.1-browsers
       - image: selenium/standalone-chrome
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Update apt
      - run: sudo apt update

      # Install Ruby for selenium/standalone-chrome
      - run: sudo apt-get --assume-yes install ruby-full

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Update apt and install firefox - not needed, already current
      - run: sudo apt install firefox

      # Download geckodriver
      - run: wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz

      # Unzip geckodriver
      - run:  gunzip -c geckodriver.tar.gz | tar xopf -

      # Make geckodriver executable
      - run: chmod +x geckodriver

      # Create directory for geckodriver
      - run: mkdir ~/calculator/gecko/

      # Move geckodriver to directory
      - run: mv geckodriver ~/calculator/gecko/

      # Verify gecko driver is in directory
      # - run: ls ~/calculator/gecko/
      # geckodriver

      # Update PATH to include directory
      - run: echo 'export PATH=~/calculator/gecko:$PATH' >> $BASH_ENV

      # View PATH
      # - run: echo $PATH
      # /home/circleci/calculator/gecko:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

      # Create directory for tests
      - run: mkdir ~/calculator/test-results/

      # Store bundle cache
      - type: cache-save
        key: collect-{{ checksum "Gemfile.lock" }}
        paths:
          - ./vendor/bundle

      # Run tests
      - type: shell
        command: rake test


      # - type: store_test_results
      #   path: ~/calculator/test-results


      # collect reports
      - store_test_results:
          path: ~/calculator/test-results
      - store_artifacts:
          path: ~/calculator/test-results
          destination: test-results